#!/bin/bash

# Variables

width=180
text="FIGlet"
filename="index.html"
verbose=0

# Parse options

for arg in "$@"
do
  case "$1" in

    "-w")
      width="$2"
      shift
      ;;

    "-t")
      text="$2"
      shift
      ;;

    "-f")
      filename="$2"
      shift
      ;;

    "-v")
      verbose=1
      ;;

    "")
      break
      ;;

    *)
      echo "Usage: $0 [-w <width>] [-t <text>] [-f <filename>]"
      exit 1
      ;;

  esac

  shift
done

# Verbose

if [ $verbose -eq 1 ]
then
  echo "width: $width"
  echo "text: $text"
  echo "filename: $filename"
fi

# Prepare HTML file

echo -e "\
<!DOCTYPE html>\n\
<html>\n\
  <head>\n\
    <meta charset=\"utf-8\">\n\
    <title>FIGlet fonts preview by CS Zach</title>\n\
  </head>\n\
  <body>\n\
    <h1>FIGlet fonts preview</h1>
    <pre>" > $filename

# Generate HTML for fonts preview

cd fonts

COMMAND="echo \"Font file: <a href=\"./fonts/{}\">{}</a>\" && echo && figlet -f \"{}\" -w \"$width\" \"$text\" && echo"
ls -1 *.[ft]lf | xargs -i sh -c "$COMMAND" 2> /dev/null >> ../"$filename"

cd ..

# Finish HTML

echo -e "\
    </pre>\n\
    <footer>
      <p style=\"text-align: center\">
        Fonts collected by <a href=\"https://github.com/xero\">xero</a>.<br>
        Preview generated by <a href=\"https://github.com/cszach\">CS Zach</a>.
      </p>
    </footer>
  </body>\n\
</html>" >> $filename

echo 'Success'
exit 0
